### ISSUE TITLE
Notebook check suggestions

### ISSUE THREAD

**Issue by jhaigh0** [cmip6moap/project-template#3]
@jatonline

I spoke with Ag and had a look over the notebooks. Here are the few changes / suggestions I have

- ex0_Create_environment.ipynb
    - 'Method 1: Install and freeze'
        - Since in the previous section we've changed kernel to the cmip6 environment, `environment_name` is no longer set. I had to go back and run the very first cell 
- ex1_Finding_CMIP6data.ipynb
    - 'Data that is not available on JASMIN'
        - I got an error that `wget` was not found (not too sure why)
- ex2a_Loading_data_with_xarray.ipynb
    - 'Loading single or multiple NetCDF files'
        - When using `open_mfdataset()` with a list comprehension, I got `ValueError: cannot guess the engine, try passing one explicitly`. I think this was because a list of lists was being constructed and parsed. To fix this I flattered the list like this;
```
import itertools
paths = [glob(f'/badc/cmip6/data/CMIP6/CMIP/MOHC/HadGEM3-GC31-LL/piControl/r1i1p1f1/Amon/{variable}/gn/latest/*.nc') for variable in ['tas', 'pr']]
paths = list(itertools.chain(*paths))
dataset = xr.open_mfdataset(paths)
```

Everything else looked good to me :)
Jonathan

**Comment by jatonline** [comment]
Hi @jhaigh0,

Thanks so much for taking the time to test this and report as an issue. It is very much appreciated! 🙌

I've taken a look and in my haste I missed a couple of things when switching between my local testing environment and the JASMIN Notebook Service.

> - ex0_Create_environment.ipynb
>     - 'Method 1: Install and freeze'
>         - Since in the previous section we've changed kernel to the cmip6 environment, `environment_name` is no longer set. I had to go back and run the very first cell 

Well spotted! I'm thinking just removing the variable replacement and just hard coding the env and file names. What do you think?

> - ex1_Finding_CMIP6data.ipynb
>     - 'Data that is not available on JASMIN'
>         - I got an error that `wget` was not found (not too sure why)

Indeed it's not there! I'll change `wget` to `curl -O` which seems to work.

> - ex2a_Loading_data_with_xarray.ipynb
>     - 'Loading single or multiple NetCDF files'
>         - When using `open_mfdataset()` with a list comprehension, I got `ValueError: cannot guess the engine, try passing one explicitly`. I think this was because a list of lists was being constructed and parsed. To fix this I flattered the list like this;

This one puzzles me a little. For me it works as-is on the Notebook Service. Do you get the error as soon as you run that cell?

```
dataset = xr.open_mfdataset(
    glob(f'/badc/cmip6/data/CMIP6/CMIP/MOHC/HadGEM3-GC31-LL/piControl/r1i1p1f1/Amon/{variable}/gn/latest/*.nc')
    for variable in ['tas', 'pr']
)
```

...or is it when you're trying to do something with the data? (And are you on the Notebook Service too? If so, what version of xarray do you have? I'm on 0.17.0) I'm just wondering whether I'm not using the function as intended with the nested lists anyway?

**Comment by jhaigh0** [comment]
Hi @jatonline 

Just re-visiting that last point, I am using the notebook service and I'm on xarray version 0.18.0. When I try to run,
```
dataset = xr.open_mfdataset(
    glob(f'/badc/cmip6/data/CMIP6/CMIP/MOHC/HadGEM3-GC31-LL/piControl/r1i1p1f1/Amon/{variable}/gn/latest/*.nc')
    for variable in ['tas', 'pr']
)
```

I get back

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-e255f0e9d131> in <module>
----> 1 dataset = xr.open_mfdataset(
      2     glob(f'/badc/cmip6/data/CMIP6/CMIP/MOHC/HadGEM3-GC31-LL/piControl/r1i1p1f1/Amon/{variable}/gn/latest/*.nc')
      3     for variable in ['tas', 'pr']
      4 )

~/.conda/envs/cmip6/lib/python3.8/site-packages/xarray/backends/api.py in open_mfdataset(paths, chunks, concat_dim, compat, preprocess, engine, data_vars, coords, combine, parallel, join, attrs_file, combine_attrs, **kwargs)
    916         getattr_ = getattr
    917 
--> 918     datasets = [open_(p, **open_kwargs) for p in paths]
    919     closers = [getattr_(ds, "_close") for ds in datasets]
    920     if preprocess is not None:

~/.conda/envs/cmip6/lib/python3.8/site-packages/xarray/backends/api.py in <listcomp>(.0)
    916         getattr_ = getattr
    917 
--> 918     datasets = [open_(p, **open_kwargs) for p in paths]
    919     closers = [getattr_(ds, "_close") for ds in datasets]
    920     if preprocess is not None:

~/.conda/envs/cmip6/lib/python3.8/site-packages/xarray/backends/api.py in open_dataset(filename_or_obj, engine, chunks, cache, decode_cf, mask_and_scale, decode_times, decode_timedelta, use_cftime, concat_characters, decode_coords, drop_variables, backend_kwargs, *args, **kwargs)
    483 
    484     if engine is None:
--> 485         engine = plugins.guess_engine(filename_or_obj)
    486 
    487     backend = plugins.get_backend(engine)

~/.conda/envs/cmip6/lib/python3.8/site-packages/xarray/backends/plugins.py in guess_engine(store_spec)
    110             warnings.warn(f"{engine!r} fails while guessing", RuntimeWarning)
    111 
--> 112     raise ValueError("cannot guess the engine, try passing one explicitly")
    113 
    114 

ValueError: cannot guess the engine, try passing one explicitly
```

All I've done here is load up the notebook, run the cell which contains;
```
from glob import glob

import matplotlib.pyplot as plt
import xarray as xr

# Set some plotting defaults
plt.rcParams['figure.figsize'] = (10, 6)
plt.rcParams['figure.dpi'] = 100
```
so xarray is imported, then run the above code in a cell.
Like I said before, I thought it might be because a list of lists is contructed and parsed to the function, but if it works for you then I'm not sure.

Everything else for the other two issues sounds good

**Comment by jatonline** [comment]
Thanks @jhaigh0, very helpful! - turns out this worked in xarray 0.17 but not 0.18. I think what I was doing with nested lists actually wasn't supported and just happened to work in 0.17. I've amended and tested as per your suggestion. Let me know if anything doesn't look right.
